# Generated by Django 5.2.3 on 2025-06-18 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_screen_showtime_booking_showtime_seat_showtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='theater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.theater'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='screen',
            name='total_seats',
            field=models.IntegerField(default=50),
        ),
    ]
