# Generated by Django 5.2.3 on 2025-06-19 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_screen_theater_alter_screen_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='screen',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='showtime',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='showtime',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='showtime',
        ),
        migrations.DeleteModel(
            name='Screen',
        ),
        migrations.DeleteModel(
            name='ShowTime',
        ),
    ]
